import React, { useState } from "react";
import { useDispatch } from "react-redux";
import toast from 'react-hot-toast'

import { useParams, useNavigate } from "react-router-dom";
import { useSelector } from "react-redux";
import { ArrowLeft,Trash2, Phone, Calendar, CheckCircle2, Clock, Mail, CheckSquare, Printer } from "lucide-react";
import { removeNote, updateContactStatus } from "../features/contacts/contactSlics";
import { addNote } from "../features/contacts/contactSlics";

const ContactDetail =() => {
    const dispatch = useDispatch()
    const { id } = useParams()
    const navigate = useNavigate()

    const handlePrint = () => {
        window.print()
    }

    const allContacts = useSelector((state) => state.contacts.items)
    const allTasks = useSelector((state) => state.tasks.items)
    const {user} = useSelector((state) => state.auth)

    const  contact = allContacts.find(c => c._id === id)
    const tasks = allTasks.filter(t => (t.contactId?._id === id) || (t.contactId === id))
    

    const [noteText, setNoteText] = useState('')
    const [isSubmitting, setIsSubmitting] = useState(false)

    if(!contact ){
        return <div style={{padding: '40px', textAlign: ' 0 auto'}}>
            Contact not found !
        </div>
    }

    const handleAddNote = async(e) => {
        e.preventDefault()
        if(!noteText.trim()) return

        setIsSubmitting(true)

        try {
            await dispatch(addNote({ id: contact._id, text: noteText })).unwrap()
            setNoteText('')
            toast.success('Note added !')
        } catch(error){
            toast.error(error || "failed to add note")
        } finally{
            setIsSubmitting(false)
        }
    }

    const handleDeleteNote = async(noteId) => {
        if(window.confirm('Are you sure want to delete this note? ')){
            try {
                await dispatch(removeNote({id: contact._id, noteId})).unwrap()
                toast.success('Note removed')
            } catch(error) {
                toast.error(err || "failed to delete note ")
            }
        }

    }

    const handleStatusChange = async (newStatus) => {
        try {
            await dispatch(updateContactStatus({ id: contact._id, status: newStatus })).unwrap()
            const message = newStatus === 'Client'
                ? 'Successfully converted to Client!'
                : 'Status reverted to Lead'

            toast.success(message)
        } catch(err) {
            toast.error(err || 'Failed to update status')
        }
    }

     return (
        
        <div style={{ width: '100%'}}>
            <button onClick={() => navigate('/contacts')} 
                style={{ display: 'flex', alignItems: 'center', gap: '8px', border: 'none', background: 'none', color: '#64748b', cursor: 'pointer', marginBottom: '20px', fontWeight: '600', fontSize:'16px'}}>
            <ArrowLeft size={18} /> Back to Contacts 
            </button>

            <button onClick={handlePrint} className="no-print"
                style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 16px', 
                backgroundColor: 'white', border: '1px solid #e2e8f0', borderRadius: '8px', 
                cursor: 'pointer', fontWeight: '600', color: '#1e293b' }}>
                <Printer size={18} /> Print Report

            </button>
            <div className="print-header" style={{ display: 'none' }}>
                <div style={{ borderBottom: '2px solid #1e293b', paddingBottom: '10px', marginBottom: '20px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
                    <div>
                        <h1 style={{ margin: 0, color: '#1e293b', fontSize: '28px' }}>Contact Summary Report</h1>
                        <p style={{ margin: 0, color: '#64748b' }}>Generated by {user? user.name: 'CRM PRO'}</p>
                    </div>
                    <div style={{ textAlign: 'right' }}>
                        <p style={{ margin: 0, fontWeight: 'bold' }}>{new Date().toLocaleDateString()}</p>
                        <p style={{ margin: 0, fontSize: '12px' }}>Confidential Client Data</p>
                    </div>
                </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '30px' }}>
                <div style={{ backgroundColor: 'white', padding: '30px', borderRadius: '16px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', height: 'fit-content' }}>
                    <div style={{ textAlign: 'center', marginBottom: '20px' }}>
                        <div style={{ width: '80px', height: '80px', backgroundColor: '#3b82f6', color: 'white', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '32px', fontWeight: 'bold', margin: '0 auto 15px' }}>
                            {contact.firstName[0]}{contact.lastName[0]}
                        </div>
                        <h2 style={{ margin: '0', color: '#1e293b'}}> {contact.firstName} {contact.lastName} </h2>
                        <span style={{ fontSize: '12px', fontWeight: '700', color: '#3b82f6', textTransform: 'uppercase' }}> {contact.status || 'Lead'} </span>
                    </div>

                    <div style={{ borderTop: '1px solid #f1f5f9', paddingTop: '20px', display: 'flex', flexDirection: 'column', gap: '15px' }}>
                        <div style={infoRowStyle}> < Mail size={16} color="#94a3b8" /> {contact.email} </div>
                        <div style={infoRowStyle}> < Mail size={16} color="#94a3b8" /> {contact.phone || 'No phone provided'} </div>
                        <div style={infoRowStyle}> < Mail size={16} color="#94a3b8" /> Added {new Date(contact.createdAt).toLocaleDateString()} </div>
                    </div>

                    <div style={{ marginTop: '30px', paddingTop: '20px', borderTop: '1px solid #f1f5f9' }}>
                        <p style={{ margin: '0 0 12px 0', fontSize: '11px', fontWeight: '700', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                            Pipeline Actions
                        </p>

                        {contact.status?.toLowerCase() === 'lead' ? (
                            <button 
                                onClick={() => handleStatusChange('Client')}
                                style={{ 
                                    width: '100%', 
                                    padding: '12px', 
                                    backgroundColor: '#10b981', 
                                    color: 'white', 
                                    border: 'none', 
                                    borderRadius: '8px', 
                                    fontWeight: '700', 
                                    cursor: 'pointer',
                                    display: 'flex',
                                    alignItems: 'center',
                                    justifyContent: 'center',
                                    gap: '8px'
                                }}
                            >
                                 Convert to Client
                            </button>
                        ) : (
                            <button 
                                onClick={() => handleStatusChange('Lead')}
                                style={{ 
                                    width: '100%', 
                                    padding: '12px', 
                                    backgroundColor: '#f59e0b', 
                                    color: 'white', 
                                    border: 'none', 
                                    borderRadius: '8px', 
                                    fontWeight: '700', 
                                    cursor: 'pointer',
                                    display: 'flex',
                                    alignItems: 'center',
                                    justifyContent: 'center',
                                    gap: '8px'
                                }}
                            >
                                 Move back to Lead
                            </button>
                        )}
                    </div>
                </div>

                <div style={{ backgroundColor: 'white', padding: '25px', borderRadius: '16px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', marginBottom: '20px'}}>
                    <h4 style={{ margin: '0 0 15px 0', color: '#1e293b', display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <CheckSquare size={18} color="#3b82f6" /> Add Internal Note
                    </h4>
                    <form onSubmit={handleAddNote}>
                    <textarea value={noteText}
                        onChange={(e) => setNoteText(e.target.value)}
                        placeholder=" Type meeting notes or update here..."
                        style={{
                            width: '100%', minHeight: '100px', padding: '12px', borderRadius:'8px',border:'1px solid #e2e8f0',
                            fontFamily:'inherit', resize: 'verticle', marginBottom: '10px', outline: 'none'
                        }} 
                    />
                    <button type="submit" disabled={isSubmitting || !noteText.trim()}
                    style={{ backgroundColor: isSubmitting ? '#94a3b8' : '#3b82f6',
                            color: 'white',
                            border: 'none',
                            padding: '10px 20px',
                            borderRadius: '8px',
                            fontWeight: '600',
                            cursor: isSubmitting ? 'not-allowed' : 'pointer',
                            transition: 'background 0.2s' 
                            }}
                    >
                        {isSubmitting ? 'saving...': 'save note'}
                    </button>

                    </form>
                </div>

                <div style={{ backgroundColor: 'white', padding: '25px', borderRadius: '16px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', marginBottom: '20px' }}>
                    <h4 style={{ margin: '0 0 20px 0', color: '#1e293b' }}>Activity History</h4>
                    {!contact.notes || contact.notes.length === 0 ? (
                        <p style={{ color: '#94a3b8', fontSize: '14px' }}>No activity recorded yet.</p>
                    ) : (
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                            {contact.notes.map((note, index) => (

                                <div key={index} style={{ borderLeft: '2px solid #e2e8f0', paddingLeft: '20px', position: 'relative' }}>
                                    <button 
                                        onClick={() => handleDeleteNote(note._id)}
                                        style={{
                                            position: 'absolute',
                                            right: '0',
                                            top: '0',
                                            background: 'none',
                                            border: 'none',
                                            color: '#94a3b8',
                                            cursor: 'pointer',
                                            padding: '5px'
                                        }}
                                        onMouseOver={(e) => e.target.style.color = '#ef4444'}
                                        onMouseOut={(e) => e.target.style.color = '#94a3b8'}
                                    >
                                        <Trash2 size={14} />
                                    </button>
                                    {/* The Timeline Dot */}
                                    <div style={{ 
                                        position: 'absolute', 
                                        left: '-6px', 
                                        top: '0', 
                                        width: '10px', 
                                        height: '10px', 
                                        backgroundColor: '#3b82f6', 
                                        borderRadius: '50%',
                                        border: '2px solid white' 
                                    }} />
                                    
                                    <p style={{ margin: '0 0 5px 0', fontSize: '14px', color: '#334155', lineHeight: '1.5' }}>
                                        {note.text}
                                    </p>
                                    <small style={{ color: '#94a3b8', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '5px' }}>
                                        <Clock size={12} /> {new Date(note.createdAt).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}
                                    </small>
                                </div>
                            ))}
                        </div>
                    )}
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                    <div style={{ backgroundColor: 'white', padding: '30px', borderRadius: '16px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' }}>
                        <h4 style={{ margin: '0 0 20px 0', color: '#1e293b' }}> Assigned Tasks </h4>
                        {tasks.length === 0 ? (
                            <p style={{ color: '#94a3b8', fontSize: '14px' }}>No tasks assigned to this contact.</p>
                        ) : (
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                                {tasks.map(task => (
                                    <div key={task._id} style={{ padding: '15px', border: '1px solid #f1f5f9', borderRadius: '10px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                        <div>
                                            <p style={{ margin: '0 0 5px 0', fontWeight: '600', color: task.status === 'Completed' ? '#94a3b8' : '#334155', textDecoration: task.status === 'Completed' ? 'line-through' : 'none' }}>
                                                {task.title}
                                            </p>
                                            <small style={{ color: '#64748b', display: 'flex', alignItems: 'center', gap: '4px' }}>
                                                <Clock size={12} /> {new Date(task.dueDate).toLocaleDateString()}
                                            </small>
                                        </div>
                                        {task.status === 'Completed' ? <CheckCircle2 color="#10b981" size={20} /> : <div style={{ width: '20px', height: '20px', borderRadius: '50%', border: '2px solid #e2e8f0' }} />}
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                </div>

            </div>
        </div>
    );
}
const infoRowStyle =  { display: 'flex', alignItems: 'center', gap: '10px', fontSize: '14px', color: '#475569' };
export default ContactDetail